### ISSUE TITLE
Failed to import cryptlex.lexactivator==3.20.11 - Undefined symbol: GetLicenseOrganizationName

### ISSUE THREAD

**Issue by evios** [cryptlex/lexactivator-python#23]
Can you please help, issue with 3.20.11 build:
```
>>> from cryptlex.lexactivator import LexActivator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/cryptlex/__init__.py", line 1, in <module>
    from cryptlex.lexactivator import *
  File "/usr/local/lib/python3.10/site-packages/cryptlex/lexactivator/__init__.py", line 1, in <module>
    from cryptlex.lexactivator.lexactivator import LexActivator, LexStatusCodes, PermissionFlags, ReleaseFlags, LexActivatorException
  File "/usr/local/lib/python3.10/site-packages/cryptlex/lexactivator/lexactivator.py", line 3, in <module>
    from cryptlex.lexactivator import lexactivator_native as LexActivatorNative
  File "/usr/local/lib/python3.10/site-packages/cryptlex/lexactivator/lexactivator_native.py", line 262, in <module>
    GetLicenseOrganizationName = library.GetLicenseOrganizationName
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/python3.10/site-packages/cryptlex/lexactivator/libs/linux/gcc/x86_64/libLexActivator.so: undefined symbol: GetLicenseOrganizationName
```

**Comment by ahmad-kemsan** [comment]
Hi Evios,

Please upgrade the package version to the latest v3.21.0
